# Generated by Django 4.2.7 on 2023-11-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_post_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
